export const categories = [
  'Waiter/Waitress',
  'Cook',
  'Chef',
  'Restaurant Manager',
  'Bartender',
  'Barback',
  'Runner',
  'Bar Manager',
  'Barista',
  'Cleaner',
  'Housekeeping',
  'Photographer',
  'Security',
  'Cashier',
  'Sales',
  'Baker',
  'Jardiner',
  'Contruction worker',
  'Mantainance worker',
  'Warehouse',
];
